apiVersion: apps/v1
kind: Deployment
metadata:
  name: html5appdeployer
  labels:
    app: html5appdeployer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html5appdeployer
  template:
    metadata:
      labels:
        app: html5appdeployer
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: html5-repo-app-host-volume
          secret:
              secretName: kyma-app-host-binding
        - name: xsuaa-volume
          secret:
            secretName: kyma2-uaa-binding
        - name: destination-volume
          secret:
            secretName: kyma-destination-binding
      containers:
        - name: html5appdeployer
          image: 860444633182.dkr.ecr.us-east-1.amazonaws.com/customfiori:4c7c0513ae0ab109f3e82db92fd4aeba9172ee17
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: appconfigxsuaa
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "32Mi"
          env:
            - name: SAP_CLOUD_SERVICE
              value: aws.kyma.fioriawskyma
            - name: BACKEND_DESTINATIONS
              value: "[{
              \"Name\":\"cap-kyma-service\",
              \"Description\":\"my kyma backend\",
              \"Type\":\"HTTP\",
              \"ProxyType\":\"Internet\",
              \"tokenServiceURLType\": \"Dedicated\",
              \"Authentication\":\"OAuth2UserTokenExchange\",
              \"HTML5.DynamicDestination\": true,
              \"clientId\": \"sb-kyma2-app!t85239\",
              \"clientSecret\":\"9d5e4d37-2ea8-40fa-a404-d186d6e62c03$0TQw3J-1DIUmpSsB73DrJc5RBfEGMRXwynb1BVNsyf4=\",
              \"tokenServiceURL\": \"https://9ec9c0b6trial.authentication.us10.hana.ondemand.com/oauth/token\",
              \"URL\":\"https://capkyma.c-89ed0f4.kyma.ondemand.com\"}]"
          volumeMounts:
            - name: html5-repo-app-host-volume
              mountPath: /etc/secrets/sapcp/html5-apps-repo/kyma-app-host-instance
              readOnly: true 
            - name: xsuaa-volume
              mountPath: /etc/secrets/sapcp/xsuaa/kyma2-uaa-instance
              readOnly: true
            - name: destination-volume
              mountPath: /etc/secrets/sapcp/destination/kyma-destination-instance
              readOnly: true
        
--- 

apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: kyma-app-host-instance
spec:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host
  parameters: {}

--- 

apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceBinding
metadata:
  name: kyma-app-host-binding
spec:
  serviceInstanceName: kyma-app-host-instance
--- 

apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: kyma-destination-instance
spec:
  serviceOfferingName: destination
  servicePlanName: lite
  parameters:
    HTML5Runtime_enabled: true
    version: 1.0.0

---
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceBinding
metadata:
  name: kyma-destination-binding
spec:
  serviceInstanceName: kyma-destination-instance

