apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyma2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyma2
  template:
    metadata:
      labels:
        app: kyma2
        version: v1
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: kyma2
          image: 860444633182.dkr.ecr.us-east-1.amazonaws.com/kyma2:64bf1c09b829077b314f7b0eef5273713b628779
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: appconfig
            - configMapRef:
                name: appconfigxsuaa
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "32Mi"
          ports:
            - name: http
              containerPort: 4004
          volumeMounts:
            - name: xsuaa-volume
              mountPath: /etc/secrets/sapcp/xsuaa/kyma2-uaa-instance
              readOnly: true
            - name: destination-volume
              mountPath: /etc/secrets/sapcp/destination/kyma2-destination-instance
      volumes:
        - name: xsuaa-volume
          secret:
            secretName: kyma2-uaa-binding
        - name: destination-volume
          secret:
            secretName: kyma2-destination-binding

---
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: kyma-xsuaa-instance
spec:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: kyma2-app
    tenant-mode: dedicated
    scopes:
      - name: "$XSAPPNAME.ADMIN"
        description: "ADMIN"
      - name: uaa.user
        description: uaa
    role-templates:
      - name: "ADMIN"
        description: "Admin Role to access the Books entityset"
        scope-references:
          - "$XSAPPNAME.ADMIN"
      - name: TOKEN_EXCHANGE
        description: Token exchange
        scope-references:
          - uaa.user
    oauth2-configuration:
      grant-types:
        - authorization_code
        - client_credentials
        - password
        - refresh_token
        - urn:ietf:params:oauth:grant-type:saml2-bearer
        - user_token
        - client_x509
        - urn:ietf:params:oauth:grant-type:jwt-bearer
      redirect-uris:
        - https://*/**
        - https://**/**
        - https://*.launchpad.cfapps.us10.hana.ondemand.com/**

---
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceBinding
metadata:
  name: kyma2-uaa-binding
  namespace: default
spec:
  serviceInstanceName: kyma2-uaa-instance

---
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: kyma2-destination-instance
spec:
  serviceOfferingName: destination
  servicePlanName: lite
  parameters:
    HTML5Runtime_enabled: true
    version: 1.0.0
---
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceBinding
metadata:
  name: kyma2-destination-binding
spec:
  serviceInstanceName: kyma2-destination-instance

---
# to expose our service outside the kyma env
apiVersion: v1
kind: Service
metadata:
  name: kyma2
  labels:
    app: kyma2
spec:
  selector:
    app: kyma2
  ports:
    - port: 4004
      targetPort: 4004
      name: http
